export const EMPLOYEE_ERROR_CODES = {
  NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  EMAIL_EXISTS: "EMPLOYEE_EMAIL_EXISTS",
  CODE_EXISTS: "EMPLOYEE_CODE_EXISTS",
};

export const SYSTEM_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};