export const ERROR_CODES = {
  EMPLOYEE: {
    NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
    EMAIL_EXISTS: 'EMPLOYEE_EMAIL_EXISTS',
    CODE_EXISTS: 'EMPLOYEE_CODE_EXISTS',
  },
  SYSTEM: {
    INTERNAL: 'INTERNAL_SERVER_ERROR',
  },
};
